import asyncio
from sqlalchemy import text
from app.db import AsyncSessionLocal

async def init_database_data():
    """
    Initialize database with initial data from dump file
    This script will populate all tables with the existing data
    """
    async with AsyncSessionLocal() as session:
        try:
            print("Starting database initialization...")
            
            # 1. Insert access_method data
            print("Upserting access_method data...")
            access_methods = [
                (1, 'spot_method'),
                (2, 'pacioos_method'),
                (3, 'dart_method'),
                (4, 'ioc_method'),
                (5, 'neon_method')
            ]
            for id_val, function in access_methods:
                await session.execute(
                    text("INSERT INTO access_method (id, function) VALUES (:id, :function) ON CONFLICT (id) DO UPDATE SET function = EXCLUDED.function"),
                    {"id": id_val, "function": function}
                )
            
            # 2. Insert status data
            print("Inserting status data...")
            statuses = [
                (1, 'active'),
                (2, 'inactive')
            ]
            for id_val, value in statuses:
                await session.execute(
                    text("INSERT INTO status (id, value) VALUES (:id, :value) ON CONFLICT (id) DO NOTHING"),
                    {"id": id_val, "value": value}
                )
            
            # 3. Insert type data
            print("Inserting type data...")
            types = [
                (1, 'buoy'),
                (2, 'weather_station'),
                (3, 'dart')
            ]
            for id_val, value in types:
                await session.execute(
                    text("INSERT INTO type (id, value) VALUES (:id, :value) ON CONFLICT (id) DO NOTHING"),
                    {"id": id_val, "value": value}
                )
            
            # 4. Insert token data
            print("Inserting token data...")
            tokens = [
                (1, 'c3abab55e2e549f02fdb683bd936c7', 'SPC'),
                (2, 'b9f2c081116e70f44152dd9aa45dcb', 'FMS'),
                (3, 'e62e5e58efac587d2c7eb4a1d938b0', 'KMS'),
                (4, 'e5c7ab12898f4414c0acf817b4bbde', 'SamoaMet'),
                (5, '743acb9023dec1ef847d5651596352', 'TongaMet'),
                (6, '99a920305541f1c38db611ebab95ba', 'TMS'),
                (7, '2a348598f294c6b0ce5f7e41e5c0f5', 'NMS'),
                (8, 'bffa4c2e02b85db7fa813d2ea69fa8cfcae5885d23a0ec47edf4382314c803d136d5ff69ffe960f426beae8d1f1f4fba7c6a4c6219b785d254a4a70369713041', 'IOC')
            ]
            for id_val, token_val, comments in tokens:
                await session.execute(
                    text("INSERT INTO token (id, token, comments) VALUES (:id, :token, :comments) ON CONFLICT (id) DO NOTHING"),
                    {"id": id_val, "token": token_val, "comments": comments}
                )
            
            # 5. Insert station data (subset of most important stations)
            print("Inserting station data...")
            stations = [         
                    (125, 'SPOT-0285', 'SPOT-0285', -19.1278, 177.95632, 'SPC', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 2, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0285&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 1),
                    (126, 'SPOT-0298', 'SPOT-0298', -19.30632, 177.96413, 'SPC', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 2, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0298&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 1),
                    (7, 'AMCHITKA - 170 NM South of Amchitka, AK', '21414', 13.3555, 144.788, 'NDBC', 'NDBC', True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', 'instrument', 3, 3, 1, 2, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (161, '178', '178', 7.081486, 158.2442, 'PACIOOS', None, True, None, None, None, 1, 2, 1, 5, 'https://erddap.cdip.ucsd.edu/erddap/tabledap/wave_agg.geoJson?station_id,time,waveHs,waveTp,waveTa,waveDp,latitude,longitude&station_id=%22STATION_ID%22&time%3E=START_TIME&time%3C=END_TIME&waveFlagPrimary=1', None),
                    (162, '196', '196', 13.6833, 144.8155, 'PACIOOS', None, True, None, None, None, 1, 2, 1, 24, 'https://erddap.cdip.ucsd.edu/erddap/tabledap/wave_agg.geoJson?station_id,time,waveHs,waveTp,waveTa,waveDp,latitude,longitude&station_id=%22STATION_ID%22&time%3E=START_TIME&time%3C=END_TIME&waveFlagPrimary=1', None),
                    (163, '219', '219', 7.629632, 134.6704, 'PACIOOS', None, True, None, None, None, 1, 2, 1, 10, 'https://erddap.cdip.ucsd.edu/erddap/tabledap/wave_agg.geoJson?station_id,time,waveHs,waveTp,waveTa,waveDp,latitude,longitude&station_id=%22STATION_ID%22&time%3E=START_TIME&time%3C=END_TIME&waveFlagPrimary=1', None),
                    (164, '273', '273', -14.2965, -170.8747, 'PACIOOS', None, True, None, None, None, 1, 2, 1, 18, 'https://erddap.cdip.ucsd.edu/erddap/tabledap/wave_agg.geoJson?station_id,time,waveHs,waveTp,waveTa,waveDp,latitude,longitude&station_id=%22STATION_ID%22&time%3E=START_TIME&time%3C=END_TIME&waveFlagPrimary=1', None),
                    (165, '276', '276', 5.24042, 163.0008, 'PACIOOS', None, True, None, None, None, 1, 2, 1, 5, 'https://erddap.cdip.ucsd.edu/erddap/tabledap/wave_agg.geoJson?station_id,time,waveHs,waveTp,waveTa,waveDp,latitude,longitude&station_id=%22STATION_ID%22&time%3E=START_TIME&time%3C=END_TIME&waveFlagPrimary=1', None),
                    (169, '121', '121', 13.3555, 144.788, 'PACIOOS', None, True, None, None, None, 1, 2, 1, 24, 'https://erddap.cdip.ucsd.edu/erddap/tabledap/wave_agg.geoJson?station_id,time,waveHs,waveTp,waveTa,waveDp,latitude,longitude&station_id=%22STATION_ID%22&time%3E=START_TIME&time%3C=END_TIME&waveFlagPrimary=1', None),
                    (127, 'SPOT-0089', 'SPOT-0089', -18.17648, 178.41657, 'SPC', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 2, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0089&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 1),
                    (128, 'SPOT-0398', 'SPOT-0398', -9.42227, 159.94742, 'SPC', None, True, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 13, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0398&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 1),
                    (129, 'SPOT-0435', 'SPOT-0435', -21.74347, 165.335, 'SPC', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 20, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0435&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 1),
                    (130, 'SPOT-1931', 'SPOT-1931', -20.50715, 165.09363, 'SPC', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 20, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-1931&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 1),
                    (131, 'SPOT-30187R', 'SPOT-30187R', -21.74685, 165.33293, 'SPC', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 20, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-30187R&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 1),
                    (132, 'SPOT-30815C', 'SPOT-30815C', -18.19448, 178.35897, 'SPC', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 2, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-30815C&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 1),
                    (133, 'SPOT-30355R', 'SPOT-30355R', -21.7311, 165.30062, 'SPC', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 20, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-30355R&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 1),
                    (134, 'SPOT-0299', 'SPOT-0299', -18.22757, 177.77305, 'FMS', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 2, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0299&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 2),
                    (135, 'SPOT-0596', 'SPOT-0596', -19.06755, 177.98447, 'FMS', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 2, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0596&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 2),
                    (136, 'SPOT-0607', 'SPOT-0607', -18.95167, 178.37548, 'FMS', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 2, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0607&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 2),
                    (4, 'This Returns Waves data', 'SPOT-31071C', -19.06193, -169.98748, 'SPC', 'SPC', True, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', 'instrument', 1, 1, 1, 2, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-31071C&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 1),
                    (138, 'SPOT-0301', 'SPOT-0301', 1.33658, 173.01658, 'KMS', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 6, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0301&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 3),
                    (139, 'SPOT-0300', 'SPOT-0300', 1.42755, 172.91135, 'KMS', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 6, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0300&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 3),
                    (140, 'SPOT-1930', 'SPOT-1930', 1.36343, 173.08808, 'KMS', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 6, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-1930&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 3),
                    (141, 'SPOT-1943', 'SPOT-1943', -5.49172, 159.69458, 'KMS', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 6, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-1943&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 3),
                    (142, 'SPOT-1906', 'SPOT-1906', -13.81498, -171.78053, 'SamoaMet', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 12, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-1906&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 4),
                    (152, 'SPOT-1905', 'SPOT-1905', -13.64255, -172.04037, 'SamoaMet', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 12, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-1905&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 4),
                    (153, 'SPOT-1611', 'SPOT-1611', -13.81497, -171.78047, 'SamoaMet', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 12, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-1611&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 4),
                    (154, 'SPOT-1951', 'SPOT-1951', -21.24395, -175.1372, 'TongaMet', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 3, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-1951&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 5),
                    (155, 'SPOT-1901', 'SPOT-1901', -26.78888, -169.9395, 'TongaMet', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 3, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-1901&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 5),
                    (156, 'SPOT-1612', 'SPOT-1612', -23.02458, -175.02327, 'TongaMet', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 3, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-1612&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 5),
                    (157, 'SPOT-30032R', 'SPOT-30032R', -21.12362, -175.19375, 'TongaMet', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 3, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-30032R&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 5),
                    (158, 'SPOT-0302', 'SPOT-0302', -6.29783, 176.3046, 'TMS', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 4, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0302&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 6),
                    (159, 'SPOT-0303', 'SPOT-0303', -8.591, 179.05518, 'TMS', None, True, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 4, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0303&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 6),
                    (160, 'SPOT-1411', 'SPOT-1411', -8.59382, 179.05637, 'TMS', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 4, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-1411&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 6),
                    (166, 'SPOT-31153C', 'SPOT-31153C', -18.9747, -169.9024667, 'NMS', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 9, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-31153C&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 7),
                    (167, 'SPOT-31071C', 'SPOT-31071C', -19.0662333, -169.98535, 'NMS', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 9, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-31071C&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 7),
                    (168, 'SPOT-31091C', 'SPOT-31091C', -19.05455, -169.9315, 'NMS', None, True, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 9, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-31091C&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 7),
                    (170, 'SPOT-0285', 'SPOT-0285', -19.1278, 177.95632, 'SPC', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 2, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0285&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 1),
                    (171, 'SPOT-0433', 'SPOT-0433', -22.57357, 166.45005, 'SPC', None, False, 'significantWaveHeight,peakPeriod,meanPeriod,peakDirection,peakDirectionalSpread,meanDirection,meanDirectionalSpread,timestamp,latitude,longitude,processing_source', 'sig_wave_height_m,peak_wave_period_s,mean_wave_period_s,peak_wave_direction_deg,peak_dir_spread_deg,mean_wave_direction_deg,mean_dir_spread_deg,obs_time_utc,lat_deg,lon_deg,data_source', None, 1, 1, 1, 20, 'https://wavefleet.spoondriftspotter.co/api/wave-data?spotterId=SPOT-0433&token=REPALCE_TOKEN_STRING&includeWaves=True&includeTrack=True&includeDirectionalMoments=True&limit=500', 1),
                    (187, 'Mendocino - 150 NM West of  Mendocino Bay, CA ', '46411', 39.34, -127.04, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (188, 'NORTHWEST APIA - 370 NM NW of Apia, Samoa ', '51425', -9.51, -176.26, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (189, 'SOUTHEAST SAIPAN - 540NM ESE of Saipan ', '52402', 11.93, 153.88, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (190, 'SOUTH PHILIPPINE SEA -725 NM West of Agana, Guam ', '52405', 12.99, 132.23, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (191, 'NZC - Offshore Gisborne Hikurangi ', '5401000', -38.2, -179.8, 'New Zealand National Emergency Management Agency by Te Pu Ao GNS Science and NIWA Taihoro Nukurangi', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (192, 'NZE - Offshore East Cape Kermadec ', '5401001', -36.05, -177.71, 'New Zealand National Emergency Management Agency by Te Pu Ao GNS Science and NIWA Taihoro Nukurangi', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (193, 'NZF - Offshore Raoul Island Kermadec ', '5401002', -29.68, -175.01, 'New Zealand National Emergency Management Agency by Te Pu Ao GNS Science and NIWA Taihoro Nukurangi', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (194, 'NZG - Offshore Tongatapu Tonga ', '5401003', -23.35, -173.4, 'New Zealand National Emergency Management Agency by Te Pu Ao GNS Science and NIWA Taihoro Nukurangi', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (195, 'NZH - Offshore Niue Tonga      ', '5401004', -20.09, -171.86, 'New Zealand National Emergency Management Agency by Te Pu Ao GNS Science and NIWA Taihoro Nukurangi', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (196, 'NZI - Offshore Samoa Tonga     ', '5401005', -16.89, -171.19, 'New Zealand National Emergency Management Agency by Te Pu Ao GNS Science and NIWA Taihoro Nukurangi', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (197, 'NZA - Offshore Wellington Hikurangi ', '5501002', -42.37, 176.91, 'New Zealand National Emergency Management Agency by Te Pu Ao GNS Science and NIWA Taihoro Nukurangi', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (198, 'NZD - Offshore Bay of Plenty Kermadec ', '5501004', -36.1, 178.6, 'New Zealand National Emergency Management Agency by Te Pu Ao GNS Science and NIWA Taihoro Nukurangi', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (199, 'NZJ - Offshore Norfolk Island New Hebrides ', '5501005', -26.67, 163.96, 'New Zealand National Emergency Management Agency by Te Pu Ao GNS Science and NIWA Taihoro Nukurangi', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (200, 'NZK - Offshore New Caledonia New Hebrides ', '5501006', -24.31, 169.5, 'New Zealand National Emergency Management Agency by Te Pu Ao GNS Science and NIWA Taihoro Nukurangi', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (202, 'Coral Sea 1     -     1285km ENE of Townsville ', '55012', -15.66, 158.45, 'Australian Bureau of Meteorology', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (201, 'NZL - Offshore Vanuatu New Hebrides ', '5501007', -19.31, 166.78, 'New Zealand National Emergency Management Agency by Te Pu Ao GNS Science and NIWA Taihoro Nukurangi', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (172, 'KURIL ISLANDS - 209NM SE of Kuril Is.  ', '21419', 44.4, 155.65, ' NDBC           ', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (173, '180 NM  West of Caldera, Chile ', '32402', -26.74, -73.98, 'Hydrographic and Oceanographic Service of the Chilean Navy (SHOA)', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (174, '120 NM NW of Valparaiso        ', '32404', -32.13, -73.8, 'Cooperative Effort DART 4G', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (175, 'NORTHWEST LIMA - 1000 NM WNW of Lima, Peru ', '32413', -7.43, -93.46, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (176, '119NM NW of Concepcion, Chile  ', '34420', -35.76, -75.24, 'Cooperative Effort DART 4G', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (177, 'NORTH SANTO DOMINGO - 328NM NNE of Santo Domingo, DO ', '41420', 23.43, -67.39, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (178, 'NORTH ST THOMAS - 300 NM North of St Thomas, Virgin Is ', '41421', 23.41, -63.89, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (179, 'SOUTHWEST BERMUDA - 200 NM SSW of Hamilton, Bermuda ', '41425', 28.64, -65.77, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (180, 'SOUTH PUERTO RICO - 230 NM Southwest of San Juan, PR ', '42407', 15.28, -68.19, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (181, 'GULF OF AMERICA - 247 NM South of New Orleans, LA ', '42409', 25.8, -89.29, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (182, 'SOUTHWEST MANZANILLO - 240 NM SW of Manzanillo, MX ', '43412', 16.02, -107.0, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (183, 'SOUTH ACAPULCO - 360NM South of Acapulco, MX ', '43413', 10.93, -100.01, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (184, 'SOUTHEAST BLOCK CANYON - 130 NM SE of Fire Island, NY ', '44402', 39.31, -70.72, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (185, 'SABLE ISLAND BANK - 437 NM E of Boston, MA ', '44403', 41.93, -61.66, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (186, 'NEWPORT - 210NM West of Coos Bay, OR ', '46407', 42.71, -128.89, 'NDBC', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (203, 'Coral Sea 2     -     870km NE of Townsville ', '55023', -14.71, 153.54, 'Australian Bureau of Meteorology', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None),
                    (204, 'Indian Ocean 2     -     630km NNE of Dampier ', '56003', -15.02, 118.07, 'Australian Bureau of Meteorology', None, True, 'time,m,lon_deg,lat_deg', 'time,water column HEIGHT,lon_deg,lat_deg', None, 3, 3, 1, None, 'https://www.ndbc.noaa.gov/dart_data.php?station=STATION_ID&startmonth=START_MONTH&startday=START_DAY&startyear=START_YEAR&endmonth=END_MONTH&endday=END_DAY&endyear=END_YEAR', None)
                ]
            
            for station_data in stations:
                await session.execute(
                    text("""
                        INSERT INTO station (
                            id, description, station_id, latitude, longitude, owner, maintainer, 
                            is_active, variable_id, variable_label, project, type_id, access_method_id, 
                            status_id, country_id, source_url, token_id
                        ) VALUES (
                            :id, :description, :station_id, :latitude, :longitude, :owner, :maintainer,
                            :is_active, :variable_id, :variable_label, :project, :type_id, :access_method_id,
                            :status_id, :country_id, :source_url, :token_id
                        ) ON CONFLICT (id) DO NOTHING
                    """),
                    {
                        "id": station_data[0],
                        "description": station_data[1],
                        "station_id": station_data[2],
                        "latitude": station_data[3],
                        "longitude": station_data[4],
                        "owner": station_data[5],
                        "maintainer": station_data[6],
                        "is_active": station_data[7],
                        "variable_id": station_data[8],
                        "variable_label": station_data[9],
                        "project": station_data[10],
                        "type_id": station_data[11],
                        "access_method_id": station_data[12],
                        "status_id": station_data[13],
                        "country_id": station_data[14],
                        "source_url": station_data[15],
                        "token_id": station_data[16]
                    }
                )
            
            # 6. Update sequences to match the data
            print("Updating sequences...")
            await session.execute(text("SELECT setval('access_method_id_seq', 5, True)"))
            await session.execute(text("SELECT setval('status_id_seq', 2, True)"))
            await session.execute(text("SELECT setval('type_id_seq', 3, True)"))
            await session.execute(text("SELECT setval('token_id_seq', 7, True)"))
            await session.execute(text("SELECT setval('station_id_seq', 171, True)"))
            
            await session.commit()
            print("Database initialization completed successfully!")
            
            # 7. Verify the data
            print("\nVerifying data...")
            result = await session.execute(text("SELECT COUNT(*) as count FROM access_method"))
            access_count = result.scalar()
            print(f"Access methods: {access_count}")
            
            result = await session.execute(text("SELECT COUNT(*) as count FROM status"))
            status_count = result.scalar()
            print(f"Statuses: {status_count}")
            
            result = await session.execute(text("SELECT COUNT(*) as count FROM type"))
            type_count = result.scalar()
            print(f"Types: {type_count}")
            
            result = await session.execute(text("SELECT COUNT(*) as count FROM token"))
            token_count = result.scalar()
            print(f"Tokens: {token_count}")
            
            result = await session.execute(text("SELECT COUNT(*) as count FROM station"))
            station_count = result.scalar()
            print(f"Stations: {station_count}")
            
        except Exception as e:
            await session.rollback()
            print(f"Database initialization failed: {str(e)}")
            raise

if __name__ == "__main__":
    asyncio.run(init_database_data()) 